language: node_js

install:
  - "npm install"
  - "npm install bower -g"
  - "bower install"


node_js:
  - "6.9.4"
# Other settings
script:
  - gulp test
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"