language: node_js
node_js:
  - 6.9.4

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

# Other settings
script:
- "gulp"
- "gulp test"

install:
- "npm install"
- "npm install bower -g"
- "bower install"