language: node_js

install:
  - "npm install"
  - "npm install bower -g"
  - "bower install"

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU


node_js:
  - "4.2"
# Other settings
script:
  - gulp test
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"