env:
  global:
    - CI=true

language: node_js
node_js:
  - 6.9.4

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"


before_install:
  - gem update --system 2.3
  - gem --version


# Other settings
script:
- "gulp dev-ci"
- "gulp test"

install:
- "npm cache clean"
- "npm install"
- "npm install bower -g"
- "bower install"
# Install scss_lint gem
- "gem update --system && gem install scss-lint"